'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Locale = 'en' | 'sv';

type Copy = Record<string, string>;

type LanguageValue = {
  locale: Locale;
  toggle: () => void;
  t: (key: string) => string;
  day: (key: string) => string;
};

const copy: Record<Locale, Copy> = {
  en: {
    language: 'SV',
    brandName: 'Salon Unique',
    atelier: 'Luxury Hair Atelier',
    heroEyebrow: 'Stockholm Luxury Hair Atelier',
    heroTitleA: 'Feminine Luxury,',
    heroTitleB: 'Styled to Captivate.',
    heroBody: "A couture women's hair experience with elegant cuts, luminous color work, and modern runway-inspired finishing.",
    bookAppointment: 'Book Appointment',
    bookNow: 'Book Now',
    viewStyles: 'View Styles',
    navServices: 'Services',
    navGallery: 'Gallery',
    navBooking: 'Booking',
    navContact: 'Contact',
    proofRating: '4.9 average rating',
    proofClients: '2,000+ happy clients',
    proofDistrict: 'Stockholm premium district',
    proofLooks: 'Featured seasonal couture looks',
    manifestoEyebrow: 'Brand Manifesto',
    manifestoTitle: 'We treat hair as couture material, not routine maintenance.',
    manifestoSubtitle: 'Every appointment is a design session where proportion, texture, and tone are tailored to your identity and lifestyle.',
    signatureEyebrow: 'Our Signature',
    signatureTitle: 'Quiet confidence, luminous finish, and refined femininity in every silhouette.',
    signatureBody: 'We combine Japanese and Korean precision techniques with modern European fashion sensibility to create looks that feel contemporary, soft, and unmistakably premium.',
    ritual1Title: 'Lumiere Contour Color',
    ritual1Text: 'Face-framing dimensional color designed around your skin tone and natural movement.',
    ritual2Title: 'Silk Structure Cut',
    ritual2Text: 'Precision cutting architecture that grows out beautifully and feels effortless daily.',
    ritual3Title: 'Velvet Finish Styling',
    ritual3Text: 'Editorial finishing pass with texture balancing, shine ritual, and camera-ready polish.',
    pressEyebrow: 'Recognition',
    pressTitle: 'Featured In',
    pressSubtitle: 'Press and awards row for brand-trust presentation in demo mode.',
    pressLogo1: 'Nordic Beauty Awards',
    pressLogo2: 'Editorial Hair Weekly',
    pressLogo3: 'Scandinavian Style',
    pressLogo4: 'Luxury Salon Guide',
    galleryEyebrow: 'Portfolio',
    galleryTitle: 'Hair Style Gallery',
    gallerySubtitle: 'Filter by style category and explore editorial-grade transformations.',
    galleryAll: 'All',
    beforeAfterReady: 'Before/After Ready',
    servicesEyebrow: 'Craft',
    servicesTitle: 'Services & Pricing',
    servicesSubtitle: 'Transparent premium pricing with estimated session durations.',
    from: 'From',
    approx: 'Approx.',
    hoursEyebrow: 'Hours',
    hoursTitle: 'Dynamic Weekly Opening Hours',
    closed: 'Closed',
    byAppointment: 'By appointment',
    openNow: 'Open Now',
    closedNow: 'Closed Now',
    closedToday: 'Closed today',
    stylistsEyebrow: 'Team',
    stylistsTitle: 'Meet the Stylists',
    yearsExperience: 'years experience',
    bookWith: 'Book with',
    reviewsEyebrow: 'Testimonials',
    reviewsTitle: 'Customer Reviews',
    reviewsSubtitle: 'Google review integration-ready carousel component.',
    contactEyebrow: 'Visit',
    contactTitle: 'Location & Contact',
    transport: 'Transport: Ostermalmstorg T-bana, 5 min walk.',
    bookingEyebrow: 'Reservation',
    bookingTitle: 'Private Concierge Booking',
    bookingSubtitle: 'Interactive demo booking preview with real flow and slot behavior for presentation.',
    demoMode: 'Demo Mode - Live booking activation is coming next',
    stylist: 'Stylist',
    service: 'Service',
    date: 'Date',
    timeSlot: 'Time Slot',
    bookingInterval: 'Booking interval: 30 min (admin-adjustable).',
    confirmPreview: 'Confirm Preview Appointment',
    demoConfirmed: 'Demo Confirmed',
    previewReserved: 'Your preview reservation is set.',
    liveBackendNext: 'Live booking backend is the next implementation step.',
    at: 'at',
    with: 'with',
    for: 'for',
    socialEyebrow: 'Social',
    socialTitle: 'Instagram / Social Feed',
    socialSubtitle: 'Follow our latest salon work, color transformations, and styling inspiration.',
    vipEyebrow: 'VIP',
    vipTitle: 'Membership / Loyalty',
    vipCardTitle: 'Atelier Prive',
    vipBody: 'UI ready for points, birthday gifts, and tier rewards architecture.',
    campaignsEyebrow: 'Campaigns',
    campaignsTitle: 'Promotions / Seasonal Campaigns',
    limited: 'Limited',
    aiEyebrow: 'AI',
    aiTitle: 'Premium Enhancements',
    aiQuizTitle: 'Style Quiz',
    aiQuizText: 'Face shape + lifestyle recommender flow.',
    aiPreviewTitle: 'AI Preview',
    aiPreviewText: 'Placeholder architecture for virtual hairstyle try-on.',
    aiTrendingTitle: 'Trending This Month',
    aiTrendingText: 'Data-driven top looks module.',
    faqEyebrow: 'FAQ',
    faqTitle: 'Frequently Asked Questions',
    footerBody: 'Luxury hair atelier in central Stockholm.',
    quickLinks: 'Quick Links',
    social: 'Social',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    terms: 'Terms',
    rightsReserved: 'All rights reserved.',
    toggleTheme: 'Toggle theme',
    backToTop: 'Back to top',
    salonMap: 'Salon map',
    categoryWomen: 'Women',
    categoryMen: 'Men',
    categoryColoring: 'Coloring',
    categoryKoreanStyle: 'Korean Style',
    categoryJapaneseStyle: 'Japanese Style',
    categoryPerm: 'Perm',
    categoryShortHair: 'Short Hair',
    categoryLongHair: 'Long Hair',
    categoryWedding: 'Wedding',
    categoryTrendyStyles: 'Trendy Styles',
    serviceCategoryHaircut: 'Haircut',
    serviceCategoryColoring: 'Coloring',
    serviceCategoryTreatment: 'Treatment',
    serviceCategoryPerm: 'Perm',
    serviceCategoryStyling: 'Styling',
    serviceCategoryScalpCare: 'Scalp Care',
    serviceSignaturePrecisionCut: 'Signature Precision Cut',
    serviceLuminousBalayage: 'Luminous Balayage',
    serviceKeratinRestorationRitual: 'Keratin Restoration Ritual',
    serviceSoftWaveKoreanPerm: 'Soft Wave Korean Perm',
    serviceEditorialBlowout: 'Editorial Blowout',
    serviceScalpDetoxCeremony: 'Scalp Detox Ceremony',
    stylistAikoIntro: 'Fashion-week trained stylist known for elegant movement and bespoke silhouettes.',
    stylistAikoSpecialties: 'Japanese precision cuts / Gloss coloring',
    stylistElenaIntro: 'Creates soft dimensional color and timeless bridal hair with couture-level finishing.',
    stylistElenaSpecialties: 'Luxury balayage / Bridal styling',
    stylistMinhoIntro: 'Specialist in modern Korean texture work and trend-forward masculine styling.',
    stylistMinhoSpecialties: 'Korean perms / Men transformations',
    reviewSophie: 'Every detail felt couture. The color blend was flawless and lasted beautifully.',
    reviewDaniel: "Best men's cut I have had in Stockholm. Refined, precise, and effortless.",
    reviewMina: 'The salon ambience is pure luxury and the team reads your style instantly.',
    promoSummerTitle: 'Summer Silk Campaign',
    promoSummerSubtitle: 'Complimentary gloss upgrade with selected color rituals.',
    faq1Q: 'How far in advance should I book?',
    faq1A: 'For prime evening and weekend slots, 1-2 weeks is recommended.',
    faq2Q: 'What is your cancellation policy?',
    faq2A: 'Changes within 24 hours may incur 50% of the booked service fee.',
    faq3Q: 'Do you offer consultations?',
    faq3A: 'Yes, we offer personalized consultations beföre color and treatment services.',
    faq4Q: 'What payment methods do you accept?',
    faq4A: 'All major cards, Apple Pay, and selected digital wallets are accepted.'
  },
  sv: {
    language: 'EN',
    brandName: 'Salon Unique',
    atelier: 'Lyxig hårateljé',
    heroEyebrow: 'Stockholm Lyxig hårateljé',
    heroTitleA: 'Feminin Lyx,',
    heroTitleB: 'Stylad för att fånga blicken.',
    heroBody: 'En couture-inspirerad hårupplevelse med eleganta klippningar, lysterfulla färgbehandlingar och modern finish.',
    bookAppointment: 'Boka tid',
    bookNow: 'Boka Nu',
    viewStyles: 'Se Frisyrer',
    navServices: 'Tjänster',
    navGallery: 'Galleri',
    navBooking: 'Bokning',
    navContact: 'Kontakt',
    proofRating: '4,9 i genomsnittligt betyg',
    proofClients: '2 000+ nöjda kunder',
    proofDistrict: 'Premiumlage i Stockholm',
    proofLooks: 'Utvalda säsongslooker',
    manifestoEyebrow: 'Vår filosofi',
    manifestoTitle: 'Vi behandlar hår som couture, inte som rutin.',
    manifestoSubtitle: 'Varje besök ar en designstund dar proportion, textur och ton anpassas efter din identitet och livsstil.',
    signatureEyebrow: 'Vår signatur',
    signatureTitle: 'Tyst självsäkerhet, lysterfull finish och forfinad femininitet i varje form.',
    signatureBody: 'Vi kombinerar japansk och koreansk precision med modern europeisk modesensibilitet för att skapa looker som känns samtida, mjuka och tydligt premium.',
    ritual1Title: 'Lumiere Contour Color',
    ritual1Text: 'Ansiktsinramande dimensionell farg skapad efter din hudton och naturliga rörelse.',
    ritual2Title: 'Silk Structure Cut',
    ritual2Text: 'Precisionsklippning med form som växer ut vackert och känns enkel varje dag.',
    ritual3Title: 'Velvet Finish Styling',
    ritual3Text: 'Editorial finish med texturbalans, glansritual och polerad kameraklar kansla.',
    pressEyebrow: 'Uppmärksamhet',
    pressTitle: 'Omnämnd i',
    pressSubtitle: 'Press- och utmärkelserad för varumärkesförtroende i demoläge.',
    pressLogo1: 'Nordic Beauty Awards',
    pressLogo2: 'Editorial Hair Weekly',
    pressLogo3: 'Scandinavian Style',
    pressLogo4: 'Luxury Salon Guide',
    galleryEyebrow: 'Portfolio',
    galleryTitle: 'Frisyrgalleri',
    gallerySubtitle: 'Filtrera efter kategori och upptäck editorial-inspirerade transformationer.',
    galleryAll: 'Alla',
    beforeAfterReady: 'Före/Efter redo',
    servicesEyebrow: 'Hantverk',
    servicesTitle: 'Tjänster & Priser',
    servicesSubtitle: 'Tydliga premiumpriser med uppskattad behandlingstid.',
    from: 'Från',
    approx: 'Ca',
    hoursEyebrow: 'Öppettider',
    hoursTitle: 'Veckans Öppettider',
    closed: 'Stängt',
    byAppointment: 'Endast tidsbokning',
    openNow: 'Öppet nu',
    closedNow: 'Stängt Nu',
    closedToday: 'Stängt idag',
    stylistsEyebrow: 'Team',
    stylistsTitle: 'Möt våra Stylister',
    yearsExperience: 'års erfarenhet',
    bookWith: 'Boka med',
    reviewsEyebrow: 'Omdömen',
    reviewsTitle: 'Kundrecensioner',
    reviewsSubtitle: 'Karusell redo för framtida Google-recensionsintegration.',
    contactEyebrow: 'Besök',
    contactTitle: 'Adress & kontakt',
    transport: 'Transport: Ostermalmstorg T-bana, 5 min promenad.',
    bookingEyebrow: 'Bokning',
    bookingTitle: 'Privat Concierge-Bokning',
    bookingSubtitle: 'Interaktiv demo av bokningsflodet med tider och tillgänglighet för presentation.',
    demoMode: 'Demo-läge - Live-bokning aktiveras i nästa steg',
    stylist: 'Stylist',
    service: 'Behandling',
    date: 'Datum',
    timeSlot: 'Tid',
    bookingInterval: 'Bokningsintervall: 30 min (admin-justerbart).',
    confirmPreview: 'Bekräfta Demo-Bokning',
    demoConfirmed: 'Demo Bekräftad',
    previewReserved: 'Din demo-bokning är registrerad.',
    liveBackendNext: 'Live-bokning med backend ar nästa implementeringssteg.',
    at: 'kl.',
    with: 'med',
    for: 'for',
    socialEyebrow: 'Socialt',
    socialTitle: 'Instagram / Socialt Flode',
    socialSubtitle: 'Följ våra senaste salongsarbeten, färgförvandlingar och stylinginspiration.',
    vipEyebrow: 'VIP',
    vipTitle: 'Medlemskap / Lojalitet',
    vipCardTitle: 'Atelier Prive',
    vipBody: 'UI redo för poäng, födelsedagserbjudanden och framtida medlemsnivåer.',
    campaignsEyebrow: 'Kampanjer',
    campaignsTitle: 'Erbjudanden / Säsongskampanjer',
    limited: 'Begränsat',
    aiEyebrow: 'AI',
    aiTitle: 'Premiumförbättringar',
    aiQuizTitle: 'Stilquiz',
    aiQuizText: 'Rekommendationer baserade pa ansiktsform och livsstil.',
    aiPreviewTitle: 'AI-Preview',
    aiPreviewText: 'Förberedd arkitektur för virtuell frisyrprovning.',
    aiTrendingTitle: 'Trendigt Denna Manad',
    aiTrendingText: 'Datadriven modul för månadens mest efterfrågade looker.',
    faqEyebrow: 'FAQ',
    faqTitle: 'Vanliga Frågor',
    footerBody: 'Lyxig haratelje i centrala Stockholm.',
    quickLinks: 'Snabblänkar',
    social: 'Socialt',
    legal: 'Juridiskt',
    privacyPolicy: 'Integritetspolicy',
    terms: 'Villkor',
    rightsReserved: 'Alla rättigheter förbehållna.',
    toggleTheme: 'Växla tema',
    backToTop: 'Till toppen',
    salonMap: 'Salongskarta',
    categoryWomen: 'Kvinnor',
    categoryMen: 'Män',
    categoryColoring: 'Färgning',
    categoryKoreanStyle: 'Koreansk Stil',
    categoryJapaneseStyle: 'Japansk Stil',
    categoryPerm: 'Permanent',
    categoryShortHair: 'Kort hår',
    categoryLongHair: 'Långt hår',
    categoryWedding: 'Bröllop',
    categoryTrendyStyles: 'Trendiga Stilar',
    serviceCategoryHaircut: 'Klippning',
    serviceCategoryColoring: 'Färgning',
    serviceCategoryTreatment: 'Behandling',
    serviceCategoryPerm: 'Permanent',
    serviceCategoryStyling: 'Styling',
    serviceCategoryScalpCare: 'Hårbottenvård',
    serviceSignaturePrecisionCut: 'Signaturklippning',
    serviceLuminousBalayage: 'Lysterfull Balayage',
    serviceKeratinRestorationRitual: 'Keratinaterstallande Ritual',
    serviceSoftWaveKoreanPerm: 'Mjuk Koreansk Permanent',
    serviceEditorialBlowout: 'Editorial Blowout',
    serviceScalpDetoxCeremony: 'Hårbotten Detox Ceremony',
    stylistAikoIntro: 'Stylist med fashion week-erfarenhet, känd för elegant rörelse och skräddarsydda silhuetter.',
    stylistAikoSpecialties: 'Japanska precisionsklippningar / Glansfärgning',
    stylistElenaIntro: 'Skapar mjuk dimensionell farg och tidlos brollopsstyling med couture-finish.',
    stylistElenaSpecialties: 'Lyxig balayage / Bröllopsstyling',
    stylistMinhoIntro: 'Specialist på modern koreansk textur och trendmedveten styling för män.',
    stylistMinhoSpecialties: 'Koreanska permanenter / Herrtransformationer',
    reviewSophie: 'Varje detalj kandes couture. Fargblandningen var felfri och holl sig vacker lange.',
    reviewDaniel: 'Bästa herrklippningen jag har fatt i Stockholm. Forfinad, precis och enkel.',
    reviewMina: 'Salongens atmosfär ar ren lyx och teamet forstar din stil direkt.',
    promoSummerTitle: 'Summer Silk Kampanj',
    promoSummerSubtitle: 'Kostnadsfri gloss-uppgradering vid utvalda färgritualer.',
    faq1Q: 'Hur langt i förväg bor jag boka?',
    faq1A: 'För populära kvälls- och helgtider rekommenderas 1-2 veckor.',
    faq2Q: 'Vad ar er avbokningspolicy?',
    faq2A: 'Ändringar inom 24 timmar kan debiteras med 50% av bokad behandling.',
    faq3Q: 'Erbjuder ni konsultation?',
    faq3A: 'Ja, vi erbjuder personliga konsultationer före färg- och behandlingsbesok.',
    faq4Q: 'Vilka betalningsmetoder accepterar ni?',
    faq4A: 'Vi  accepterar de flesta kort, Apple Pay och utvalda digitala plånböcker.'
  }
};

const dayLabels: Record<Locale, Record<string, string>> = {
  en: { Monday: 'Monday', Tuesday: 'Tuesday', Wednesday: 'Wednesday', Thursday: 'Thursday', Friday: 'Friday', Saturday: 'Saturday', Sunday: 'Sunday' },
  sv: { Monday: 'Måndag', Tuesday: 'Tisdag', Wednesday: 'Onsdag', Thursday: 'Torsdag', Friday: 'Fredag', Saturday: 'Lördag', Sunday: 'Söndag' }
};

const LanguageContext = createContext<LanguageValue>({ locale: 'en', toggle: () => {}, t: (key: string) => key, day: (key: string) => key });

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [locale, setLocale] = useState<Locale>('en');

  useEffect(() => {
    const stored = localStorage.getItem('locale');
    if (stored === 'en' || stored === 'sv') setLocale(stored);
  }, []);

  useEffect(() => {
    document.documentElement.lang = locale;
  }, [locale]);

  const toggle = () => {
    setLocale((prev) => {
      const next: Locale = prev === 'en' ? 'sv' : 'en';
      localStorage.setItem('locale', next);
      return next;
    });
  };

  const value = useMemo(
    () => ({
      locale,
      toggle,
      t: (key: string) => copy[locale][key] ?? key,
      day: (key: string) => dayLabels[locale][key] ?? key
    }),
    [locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
